---
name: HTML-Revelation
version: 1.01
author:
  - 'Ron Savage <ron@savage.net.au>'
abstract: Reveal HTML document structure in a myriad of colors
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  File::Spec: 0
  HTML::Entities::Interpolate: 0
  HTML::Tagset: 0
  HTML::TreeBuilder: 0
  List::Cycle: 0
  accessors::classic: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  HTML::Revelation:
    file: lib/HTML/Revelation.pm
    version: 1.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
